# docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres
    container_name: sell_here_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - data:/var/lib/postgresql/data
volumes:
  data: