version: 2

sources:
  - name: sell_here
    description: "This is the postgres original database"
    tables:
      - name: customers
      - name: products
      - name: reseller_products
      - name: reseller
      - name: sales

  - name: external_data
    description: "Sources ingested directly into our datawarehouse"
    tables:
      - name: external_reseller_sales
